### ISSUE TITLE
[BUG] Cadastro de impressora passa modeloId errado

### ISSUE THREAD

**Issue by lbvx** [fga-eps-mds/2024.1-PrintGo-FrontEnd#59]
Na página de cadastro de impressora, no modeloId referente ao id do Padrão do equipamento, está sendo passado o nome do modelo e não o id numérico.

![image](https://github.com/user-attachments/assets/97b96a9d-313d-4efc-9bd3-eaf4e0d41b78)

**Comment by GRVial** [comment]
Também corrigi o problema que ocorria ao ter mais de um modelo por marca. Anteriormente não havia como fazer a distinção de qual modelo usar caso tivesse mais de um por marca.
